FROM node:20-alpine
WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm install --omit=dev

COPY . .

ENV NODE_ENV=production
EXPOSE 3001

# Copy entrypoint and make executable
COPY ./scripts/docker-entrypoint.sh /usr/src/app/scripts/docker-entrypoint.sh
RUN chmod +x /usr/src/app/scripts/docker-entrypoint.sh

ENTRYPOINT ["/usr/src/app/scripts/docker-entrypoint.sh"]
