// src/app/(auth)/layout.tsx

// layout do módulo de autenticação, para rota de login

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "App Contas | Login",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
