// layout do módulo de autenticação, para rota de login

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App | Login",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              style: {
                background: '#10b981', // 33cc33 -  10b981
                color: '#fff',
              },
              iconTheme: {
                primary: '#33cc33',
                secondary: '#fff',
              },
            },
            error: {
              style: {
                background: '#ef5555', // ff3333 - ef4444
                color: '#fff',
              },
              iconTheme: {
                primary: '#ff3333',
                secondary: '#fff',
              },
            }
          }}
        />
      </body>
    </html>
  );
}
